import { VerifierPlugin, PluginType, type PluginMetadata, type PluginResponse, type SupportedExplorersResult, type VerifyParams, type CheckVerificationParams, type GetCreationTxParams, type VerifyStatusResult, type CreationTxResult, type VerifierOperation } from '../../shared/index.ts';
import { runPluginCLI } from '../../shared/plugin-runner.js';
declare const PLUGIN_VERSION: string;
type WithConfig<T> = T & { config?: Record<string, unknown> };
const endpoint = (o: { explorerUrl: string; apiUrl?: string }) => o.apiUrl ?? `${o.explorerUrl.replace(/\/$/, '')}/api`;
const key = (o?: Record<string, unknown>) => typeof o?.apiKey === 'string' ? o.apiKey : '';
const ok = <T>(data: T): PluginResponse<T> => ({ success: true, data });
const fail = (code: string, retryable = true, message?: string): PluginResponse<any> => ok({ status: 'failed', retryable, detail: message ? `${code}: ${message.slice(0, 300)}` : code });
async function request(url: string, init?: RequestInit): Promise<any> { const response = await fetch(url, init); if (!response.ok) throw new Error(); return response.json(); }
const append = (url: string, query: URLSearchParams) => `${url}${url.includes('?') ? '&' : '?'}${query}`;
export class BlockscoutPlugin extends VerifierPlugin {
  protected static getMetadata(): PluginMetadata { return { id: 'blockscout', types: [PluginType.VERIFIER], name: 'Blockscout', version: PLUGIN_VERSION, baseImage: 'ignite/verifier_blockscout:latest', permissions: [{ id: 'net', description: 'Call the Blockscout API.' }], configFields: [{ key: 'apiKey', label: 'API Key', type: 'string', secret: true, required: false, perChain: true, description: 'Optional Blockscout API key.' }] }; }
  async getSupportedExplorers(): Promise<PluginResponse<SupportedExplorersResult>> { return ok({ explorers: [], urlPatterns: ['blockscout'] }); }
  async verify(options: WithConfig<VerifyParams>): Promise<PluginResponse<VerifyStatusResult>> { try { const form = new URLSearchParams({ module:'contract', action:'verifysourcecode', contractaddress:options.address, sourceCode:JSON.stringify(options.standardJsonInput), codeformat:'solidity-standard-json-input', contractname:options.contractIdentifier, compilerversion:options.solcVersion, constructorArguements:options.encodedConstructorArgs.replace(/^0x/i,''), apikey:key(options.config) }); const json = await request(endpoint(options), {method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form}); const value=String(json.result??''); if(/contract source code already verified|already verified/i.test(value)) return ok({status:'already-verified'}); if(/already verifying|is already being verified|pending in queue(?: at submit)?/i.test(value)) return ok({status:'failed',retryable:true,detail:'verification already in progress'}); const notIndexed=/unable to locate contractcode|not.{0,10}indexed|does not exist/i.test(value); const transient=/rate limit|temporar/i.test(value); return json.status==='1'?ok({status:'pending',pollTicket:value}):fail(notIndexed||transient?'RETRYABLE':'SUBMIT_FAILED',notIndexed||transient,value); } catch{return fail('NETWORK_ERROR');} }
  async checkVerification(options: WithConfig<CheckVerificationParams>): Promise<PluginResponse<VerifyStatusResult>> { try { const json=await request(append(endpoint(options),new URLSearchParams({module:'contract',action:'checkverifystatus',guid:options.pollTicket,apikey:key(options.config)}))); const value=String(json.result??''); if(/Pending/i.test(value))return ok({status:'pending'}); if(/Pass - Verified/i.test(value))return ok({status:'verified'}); if(/Already Verified/i.test(value))return ok({status:'already-verified'}); return fail('VERIFICATION_FAILED',/rate limit|temporar/i.test(value),value); }catch{return fail('NETWORK_ERROR');} }
  async getCreationTx(options: WithConfig<GetCreationTxParams>): Promise<PluginResponse<CreationTxResult>> { try { const json=await request(append(endpoint(options),new URLSearchParams({module:'contract',action:'getcontractcreation',contractaddresses:options.address,apikey:key(options.config)}))); const txHash=Array.isArray(json.result)?json.result[0]?.txHash:undefined; return ok(typeof txHash==='string'?{txHash}:null); }catch{return fail('NETWORK_ERROR');} }
}
const plugin = new BlockscoutPlugin(); export default plugin; runPluginCLI<VerifierOperation>(plugin);
