// Custom error types for Ignite

export class IgniteError extends Error {
  readonly code: string;
  readonly details?: Record<string, unknown>;

  constructor(
    message: string,
    code: string,
    details?: Record<string, unknown>
  ) {
    super(message);
    this.name = 'IgniteError';
    this.code = code;
    this.details = details;
  }
}

export class ProfileError extends IgniteError {
  constructor(
    message: string,
    code: string,
    details?: Record<string, unknown>
  ) {
    super(message, code, details);
    this.name = 'ProfileError';
  }
}

export class FileSystemError extends IgniteError {
  constructor(
    message: string,
    code: string,
    details?: Record<string, unknown>
  ) {
    super(message, code, details);
    this.name = 'FileSystemError';
  }
}

export class PluginError extends IgniteError {
  constructor(
    message: string,
    code: string,
    details?: Record<string, unknown>
  ) {
    super(message, code, details);
    this.name = 'PluginError';
  }
}

// Error codes — the single registry. API reply helpers only accept members
// of this object, so a typo'd or unregistered code is a compile error.
export const ErrorCodes = {
  // Profile errors
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROFILE_ALREADY_EXISTS: 'PROFILE_ALREADY_EXISTS',
  INVALID_PROFILE_NAME: 'INVALID_PROFILE_NAME',
  CANNOT_DELETE_DEFAULT_PROFILE: 'CANNOT_DELETE_DEFAULT_PROFILE',
  CANNOT_DELETE_ACTIVE_PROFILE: 'CANNOT_DELETE_ACTIVE_PROFILE',
  CANNOT_DELETE_LAST_PROFILE: 'CANNOT_DELETE_LAST_PROFILE',
  PROFILE_LIST_ERROR: 'PROFILE_LIST_ERROR',
  PROFILE_ARCHIVE_LIST_ERROR: 'PROFILE_ARCHIVE_LIST_ERROR',
  PROFILE_GET_ERROR: 'PROFILE_GET_ERROR',
  PROFILE_CREATE_ERROR: 'PROFILE_CREATE_ERROR',
  PROFILE_SWITCH_ERROR: 'PROFILE_SWITCH_ERROR',
  PROFILE_UPDATE_ERROR: 'PROFILE_UPDATE_ERROR',
  PROFILE_ARCHIVE_ERROR: 'PROFILE_ARCHIVE_ERROR',
  PROFILE_RESTORE_ERROR: 'PROFILE_RESTORE_ERROR',
  PROFILE_DELETE_ERROR: 'PROFILE_DELETE_ERROR',
  PROFILE_REPOS_LIST_ERROR: 'PROFILE_REPOS_LIST_ERROR',
  PROFILE_REPO_SAVE_ERROR: 'PROFILE_REPO_SAVE_ERROR',
  PROFILE_REPO_DELETE_ERROR: 'PROFILE_REPO_DELETE_ERROR',
  REPO_ALREADY_EXISTS: 'REPO_ALREADY_EXISTS',

  // File system errors
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  INVALID_JSON: 'INVALID_JSON',
  WRITE_FAILED: 'WRITE_FAILED',
  READ_FAILED: 'READ_FAILED',
  INVALID_PATH: 'INVALID_PATH',
  LIST_DIRECTORY_ERROR: 'LIST_DIRECTORY_ERROR',

  // Plugin registry/install errors
  PLUGIN_NOT_FOUND: 'PLUGIN_NOT_FOUND',
  PLUGIN_INSTALL_CONFLICT: 'PLUGIN_INSTALL_CONFLICT',
  PLUGIN_INSTALL_INVALID: 'PLUGIN_INSTALL_INVALID',
  PLUGIN_INSTALL_REJECTED: 'PLUGIN_INSTALL_REJECTED',
  PLUGIN_INSTALL_ERROR: 'PLUGIN_INSTALL_ERROR',
  PLUGIN_UNINSTALL_REJECTED: 'PLUGIN_UNINSTALL_REJECTED',
  PLUGIN_UNINSTALL_ERROR: 'PLUGIN_UNINSTALL_ERROR',
  PLUGIN_UPDATE_INVALID: 'PLUGIN_UPDATE_INVALID',
  PLUGIN_IMAGE_MISSING: 'PLUGIN_IMAGE_MISSING',
  PLUGIN_REBUILD_FAILED: 'PLUGIN_REBUILD_FAILED',
  PLUGIN_LIST_ERROR: 'PLUGIN_LIST_ERROR',
  PLUGIN_GET_ERROR: 'PLUGIN_GET_ERROR',
  PLUGIN_VERSIONS_ERROR: 'PLUGIN_VERSIONS_ERROR',
  GIT_INSPECT_FAILED: 'GIT_INSPECT_FAILED',

  // Execution / permission errors
  PERMISSION_REQUIRED: 'PERMISSION_REQUIRED',
  PERMISSION_NOT_REQUESTED: 'PERMISSION_NOT_REQUESTED',
  OPERATION_EXECUTION_FAILED: 'OPERATION_EXECUTION_FAILED',
  OPERATION_NOT_DECLARED: 'OPERATION_NOT_DECLARED',
  OPERATION_RESERVED: 'OPERATION_RESERVED',
  RESERVED_OPTION_KEY: 'RESERVED_OPTION_KEY',
  PLUGIN_RESULT_TOO_LARGE: 'PLUGIN_RESULT_TOO_LARGE',
  DEPLOYMENT_TYPE_OP_FAILED: 'DEPLOYMENT_TYPE_OP_FAILED',
  DEPLOYMENT_HOOK_OP_FAILED: 'DEPLOYMENT_HOOK_OP_FAILED',
  WORKFLOW_RESOLUTION_MISMATCH: 'WORKFLOW_RESOLUTION_MISMATCH',
  WORKFLOW_HOOK_NOT_DECLARED: 'WORKFLOW_HOOK_NOT_DECLARED',
  WORKFLOW_ARTIFACT_DRIFT: 'WORKFLOW_ARTIFACT_DRIFT',
  WORKFLOW_HOOKS_UNAVAILABLE: 'WORKFLOW_HOOKS_UNAVAILABLE',
  UNKNOWN_PARAM_KEY: 'UNKNOWN_PARAM_KEY',

  // Job errors
  INTERRUPTED: 'INTERRUPTED',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',

  // Trust / auth errors
  TRUST_LIST_ERROR: 'TRUST_LIST_ERROR',
  TRUST_UPDATE_ERROR: 'TRUST_UPDATE_ERROR',
  TRUST_IMMUTABLE: 'TRUST_IMMUTABLE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  HOST_NOT_ALLOWED: 'HOST_NOT_ALLOWED',

  // System
  SYSTEM_INFO_ERROR: 'SYSTEM_INFO_ERROR',
  FACTORY_RESET_ERROR: 'FACTORY_RESET_ERROR',

  // Compiler route errors
  NOT_A_COMPILER_PLUGIN: 'NOT_A_COMPILER_PLUGIN',
  NO_COMPILER_PLUGINS: 'NO_COMPILER_PLUGINS',
  UNKNOWN_PLUGIN: 'UNKNOWN_PLUGIN',
  INSTALL_FAILED: 'INSTALL_FAILED',
  COMPILE_FAILED: 'COMPILE_FAILED',
  ARTIFACT_LISTING_ERROR: 'ARTIFACT_LISTING_ERROR',
  ARTIFACT_NOT_FOUND: 'ARTIFACT_NOT_FOUND',
  ARTIFACT_PARSE_ERROR: 'ARTIFACT_PARSE_ERROR',
  ARTIFACT_DATA_ERROR: 'ARTIFACT_DATA_ERROR',

  // Repo-manager route errors
  INIT_ERROR: 'INIT_ERROR',
  REPO_CHECK_ERROR: 'REPO_CHECK_ERROR',
  GET_BRANCHES_ERROR: 'GET_BRANCHES_ERROR',
  CHECKOUT_BRANCH_ERROR: 'CHECKOUT_BRANCH_ERROR',
  CHECKOUT_COMMIT_ERROR: 'CHECKOUT_COMMIT_ERROR',
  PULL_ERROR: 'PULL_ERROR',
  RESET_ERROR: 'RESET_ERROR',
  INFO_ERROR: 'INFO_ERROR',
  GET_FILE_ERROR: 'GET_FILE_ERROR',
  SUSPICIOUS_PATH_PATTERN: 'SUSPICIOUS_PATH_PATTERN',

  // Chain registry / RPC store errors
  CHAIN_LIST_ERROR: 'CHAIN_LIST_ERROR',
  CHAIN_NOT_FOUND: 'CHAIN_NOT_FOUND',
  CHAIN_NOT_CUSTOM: 'CHAIN_NOT_CUSTOM',
  CHAIN_UPSERT_ERROR: 'CHAIN_UPSERT_ERROR',
  CHAIN_DELETE_ERROR: 'CHAIN_DELETE_ERROR',
  CHAINLIST_REFRESH_ERROR: 'CHAINLIST_REFRESH_ERROR',
  RPC_LIST_ERROR: 'RPC_LIST_ERROR',
  RPC_ALREADY_EXISTS: 'RPC_ALREADY_EXISTS',
  RPC_NOT_FOUND: 'RPC_NOT_FOUND',
  INVALID_RPC_URL: 'INVALID_RPC_URL',
  RPC_ADD_ERROR: 'RPC_ADD_ERROR',
  RPC_DELETE_ERROR: 'RPC_DELETE_ERROR',
  RPC_VERIFY_ERROR: 'RPC_VERIFY_ERROR',
  RPC_ENDPOINT_NOT_FOUND: 'RPC_ENDPOINT_NOT_FOUND',

  // Signer / transaction errors
  SIGNED_TX_MISMATCH: 'SIGNED_TX_MISMATCH',
  ARG_TYPE_MISMATCH: 'ARG_TYPE_MISMATCH',
  SIGNER_ADDRESS_MISMATCH: 'SIGNER_ADDRESS_MISMATCH',
  SIGNER_ACCOUNT_NOT_FOUND: 'SIGNER_ACCOUNT_NOT_FOUND',
  SIGNER_SEND_ERROR: 'SIGNER_SEND_ERROR',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  RECEIPT_TIMEOUT: 'RECEIPT_TIMEOUT',
  FRONTEND_RUNTIME_UNAVAILABLE: 'FRONTEND_RUNTIME_UNAVAILABLE',

  // Deployment run errors
  DEPLOYMENT_RUN_NOT_FOUND: 'DEPLOYMENT_RUN_NOT_FOUND',
  STALE_RESOLVE: 'STALE_RESOLVE',
  ILLEGAL_RESOLVE: 'ILLEGAL_RESOLVE',
  DEPLOYMENT_VALIDATION_FAILED: 'DEPLOYMENT_VALIDATION_FAILED',
  PLUGIN_PREPARE_MISMATCH: 'PLUGIN_PREPARE_MISMATCH',
  POINTER_SUGGESTIONS_FAILED: 'POINTER_SUGGESTIONS_FAILED',
  WORKFLOW_PROMOTION_FAILED: 'WORKFLOW_PROMOTION_FAILED',
  WORKFLOW_UPDATE_CHECK_FAILED: 'WORKFLOW_UPDATE_CHECK_FAILED',

  // Plugin config / secret store errors
  CONFIG_GET_ERROR: 'CONFIG_GET_ERROR',
  CONFIG_SET_ERROR: 'CONFIG_SET_ERROR',
  CONFIG_UNKNOWN_FIELD: 'CONFIG_UNKNOWN_FIELD',
  CONFIG_FIELD_IS_SECRET: 'CONFIG_FIELD_IS_SECRET',
  SECRET_SET_ERROR: 'SECRET_SET_ERROR',
  SECRET_NOT_DECLARED: 'SECRET_NOT_DECLARED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
