import { VerifierPlugin, PluginType, type PluginMetadata, type PluginResponse, type VerifierOperation, type SupportedExplorersResult, type VerifyParams, type VerifyStatusResult, type CheckVerificationParams, type GetCreationTxParams, type CreationTxResult } from '../../shared/index.ts';
import { runPluginCLI } from '../../shared/plugin-runner.js';
declare const PLUGIN_VERSION: string;
type WithConfig<T> = T & { config?: Record<string, unknown> }; const base = (o: {apiUrl?:string; config?:Record<string,unknown>}) => o.apiUrl ?? (typeof o.config?.apiUrl === 'string' ? o.config.apiUrl : 'https://sourcify.dev/server');
export class SourcifyPlugin extends VerifierPlugin {
 protected static getMetadata(): PluginMetadata { return { id:'sourcify', types:[PluginType.VERIFIER], name:'Sourcify', version:PLUGIN_VERSION, baseImage:'ignite/verifier_sourcify:latest', permissions:[{ id: 'net', description: 'Call the Sourcify API.' }], configFields:[{key:'apiUrl',label:'Server URL',type:'string',required:false,description:'Sourcify server URL.'}] }; }
 async getSupportedExplorers(options?: {config?:Record<string,unknown>}): Promise<PluginResponse<SupportedExplorersResult>> { try { const json=await jsonFetch(`${base(options ?? {})}/chains`); const chains=Array.isArray(json)?json:(Array.isArray(json?.chains)?json.chains:[]); return ok({explorers:chains.map((x:any)=>({chainId:Number(x.chainId ?? x),explorerUrl:base(options ?? {}),label:'Sourcify'})).filter((x:any)=>Number.isInteger(x.chainId)&&x.chainId>0),urlPatterns:['sourcify']}); } catch{return fail('NETWORK_ERROR');} }
 async verify(options: WithConfig<VerifyParams>): Promise<PluginResponse<VerifyStatusResult>> { try { const response=await fetch(`${base(options)}/v2/verify/${options.chainId}/${options.address}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stdJsonInput:options.standardJsonInput,compilerVersion:options.solcVersion,contractIdentifier:options.contractIdentifier,...(options.creationTxHash?{creationTransactionHash:options.creationTxHash}:{})})}); if(response.status===409)return ok({status:'already-verified'}); if(!response.ok)throw new Error(); const json=await response.json() as any; return typeof json.verificationId==='string'?ok({status:'pending',pollTicket:json.verificationId}):fail('SUBMIT_FAILED',false); }catch{return fail('NETWORK_ERROR');} }
 async checkVerification(options: WithConfig<CheckVerificationParams>): Promise<PluginResponse<VerifyStatusResult>> { try { const json=await jsonFetch(`${base(options)}/v2/verify/${options.pollTicket}`); const state=String(json.status ?? json.state ?? ''); const level=String(json.match ?? json.matchLevel ?? ''); if(/pending|queued/i.test(state))return ok({status:'pending'}); if(/verified|complete|success/i.test(state))return ok({status:'verified',detail:level?`match:${level}`:undefined}); return ok({status:'failed',retryable:false,detail:'VERIFICATION_FAILED'}); }catch{return fail('NETWORK_ERROR');} }
 async getCreationTx(_options: GetCreationTxParams): Promise<PluginResponse<CreationTxResult>> { return ok(null); }
}
async function jsonFetch(url:string){const response=await fetch(url);if(!response.ok)throw new Error();return response.json();} function ok<T>(data:T):PluginResponse<T>{return {success:true,data};} function fail(code:string,retryable=true):PluginResponse<any>{return ok({status:'failed',retryable,detail:code});} const plugin=new SourcifyPlugin(); export default plugin; runPluginCLI<VerifierOperation>(plugin);
